# Site settings
email: silqwer@naver.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: UA-113776431-1

# SEO settings
title: My Portfolio
description: Hi, My name is KimYongHo
url: ""
twitter_username: 
default_img: 

# Profile settings
name: KimYongHo
profile_img: 
profile: 
social:https://www.facebook.com/yongho.kim.58
github:https://github.com/silqwer

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
