# Site settings
email: silqwer@naver.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: UA-113776431-1

# SEO settings
title: My Portfolio
description: Hi, My name is KimYongHo
url: ""
twitter_username: 
default_img: 

# Profile settings
name: KimYongHo
profile_img: /assets/img/profile/me.png
profile: 4년 차 웹 개발자로 서버사이드 개발 및 프론트엔트 개발에서 다양한 경험이 있습니다. java, Spring Framework, javaScript, git, svn, MySQL, Oracle 등의 기술을 사용해서 서비스를 개발하고 및 유지보수한 경험이 있으며 항상 개발 프로세서와 개발 문화를개선하려 노력하고 있습니다.
social:
	github: https://github.com/silqwer
	facebook:  https://www.facebook.com/yongho.kim.58
	
# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
